name: FFmpeg

on:
  workflow_dispatch:
    inputs:
      ffmpeg-version:
        description: The version of FFmpeg
        required: true
        default: master
      x264-version:
        description: The version of x264
        required: true
        default: stable
      x265-version:
        description: The version of x265
        required: true
        default: 3.5
      opus-version:
        description: The version of opus
        required: true
        default: 1.3.1
      svtav1-version:
        description: The version of svt-av1
        required: true
        default: master
      prefix:
        description: The prefix path of FFmpeg
        required: true
        default: /opt/ffmpeg
      cache_id:
        description: The build id for caches
        required: true
        default: "1"

jobs:
  x264:
    name: "${{ github.job }}"
    runs-on: ubuntu-latest
    continue-on-error: true
    env:
      VERSION: ${{ github.event.inputs.x264-version }}
      PREFIX: ${{ github.event.inputs.prefix }}
      
    steps:
      - name: Get number of CPU cores
        uses: SimenB/github-actions-cpu-cores@v1
        id: cpu-cores
    
      - uses: actions/cache@v3
        id: cache
        with:
          path: |
            ${{ github.workspace }}/src
            ${{ github.workspace }}/build
            ${{ github.event.inputs.prefix }}
          key: ${{ github.job }}-${{ runner.os }}-${{ github.event.inputs.cache_id }}
          
      - name: Install build dependency
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          sudo apt-get install -qq -y nasm yasm
          
      - name: Download sources
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          git clone -b ${{ env.VERSION }} --depth 1 https://code.videolan.org/videolan/x264 src
          mkdir build

      - name: Configure
        if: steps.cache.outputs.cache-hit != 'true'
        working-directory: build
        run: |
          ../src/configure --prefix=${{ env.PREFIX }} --disable-shared --enable-static --disable-cli --disable-opencl --enable-pic
          
      - name: Build
        if: steps.cache.outputs.cache-hit != 'true'
        working-directory: build
        run: |
          make -j${{ steps.cpu-cores.outputs.count }}
      
      - name: Install
        if: steps.cache.outputs.cache-hit != 'true'
        working-directory: build
        run: |
          make install
          
      - name: Archive
        run: |
          tar -cJvf build/${{ github.job }}.tar.xz -C ${{ env.PREFIX }} .
         
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ github.job }}
          path: build/${{ github.job }}.tar.xz
          retention-days: 3
          
  x265:
    name: "${{ github.job }}"
    runs-on: ubuntu-latest
    continue-on-error: true
    env:
      VERSION: ${{ github.event.inputs.x265-version }}
      PREFIX: ${{ github.event.inputs.prefix }}
      
    steps:
      - name: Get number of CPU cores
        uses: SimenB/github-actions-cpu-cores@v1
        id: cpu-cores
    
      - uses: actions/cache@v3
        id: cache
        with:
          path: |
            ${{ github.workspace }}/src
            ${{ github.workspace }}/build
            ${{ github.event.inputs.prefix }}
          key: ${{ github.job }}-${{ runner.os }}-${{ github.event.inputs.cache_id }}

      - name: Install build dependency
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          sudo apt-get install -qq -y nasm yasm
          
      - name: Download sources
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          git clone -b ${{ env.VERSION }} --depth 1 https://bitbucket.org/multicoreware/x265_git src
          mkdir build

      - name: Configure
        if: steps.cache.outputs.cache-hit != 'true'
        working-directory: src/build/linux
        run: |
          cmake ../../source -DCMAKE_INSTALL_PREFIX=${{ env.PREFIX }} -DENABLE_SHARED:BOOL=OFF -DSTATIC_LINK_CRT:BOOL=ON -DENABLE_CLI:BOOL=OFF
          
      - name: Build
        if: steps.cache.outputs.cache-hit != 'true'
        working-directory: src/build/linux
        run: |
          make -j${{ steps.cpu-cores.outputs.count }} install
          
      - name: Archive
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          tar -cJvf build/${{ github.job }}.tar.xz -C ${{ env.PREFIX }} .
         
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ github.job }}
          path: build/${{ github.job }}.tar.xz
          retention-days: 3

  opus:
    name: "${{ github.job }}"
    runs-on: ubuntu-latest
    continue-on-error: true
    env:
      VERSION: ${{ github.event.inputs.opus-version }}
      PREFIX: ${{ github.event.inputs.prefix }}
      
    steps:
      - name: Get number of CPU cores
        uses: SimenB/github-actions-cpu-cores@v1
        id: cpu-cores
    
      - uses: actions/cache@v3
        id: cache
        with:
          path: |
            ${{ github.workspace }}/src
            ${{ github.workspace }}/build
            ${{ github.event.inputs.prefix }}
          key: ${{ github.job }}-${{ runner.os }}-${{ github.event.inputs.cache_id }}
    
      - name: Download sources
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          curl -sSL https://archive.mozilla.org/pub/opus/opus-${{ env.VERSION }}.tar.gz -o opus.tar.gz
          tar -xf opus.tar.gz
          rm opus.tar.gz
          mv opus* src
          mkdir build

      - name: Configure
        if: steps.cache.outputs.cache-hit != 'true'
        working-directory: build
        run: |
          ../src/configure --prefix=${PREFIX} --disable-shared --enable-static
          
      - name: Build
        if: steps.cache.outputs.cache-hit != 'true'
        working-directory: build
        run: |
          make -j${{ steps.cpu-cores.outputs.count }}
          
      - name: Install
        if: steps.cache.outputs.cache-hit != 'true'
        working-directory: build
        run: |
          make install
          
      - name: Archive
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          tar -cJvf build/${{ github.job }}.tar.xz -C ${{ env.PREFIX }} .
         
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ github.job }}
          path: build/${{ github.job }}.tar.xz
          retention-days: 3
          
  svtav1:
    name: "${{ github.job }}"
    runs-on: ubuntu-latest
    continue-on-error: true
    env:
      VERSION: ${{ github.event.inputs.svtav1-version }}
      PREFIX: ${{ github.event.inputs.prefix }}
      
    steps:
      - name: Get number of CPU cores
        uses: SimenB/github-actions-cpu-cores@v1
        id: cpu-cores
    
      - uses: actions/cache@v3
        id: cache
        with:
          path: |
            ${{ github.workspace }}/src
            ${{ github.workspace }}/build
            ${{ github.event.inputs.prefix }}
          key: ${{ github.job }}-${{ runner.os }}-${{ github.event.inputs.cache_id }}

      - name: Install build dependency
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          sudo apt-get install -qq -y nasm yasm
    
      - name: Download sources
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          git clone -b ${{ env.VERSION }} --depth=1 https://gitlab.com/AOMediaCodec/SVT-AV1.git src
          mkdir build

      - name: Configure
        if: steps.cache.outputs.cache-hit != 'true'
        working-directory: build
        run: |
          cmake ../src -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=${{ env.PREFIX }} \
            -DBUILD_SHARED_LIBS="OFF" \
            -DCMAKE_EXE_LINKER_FLAGS="-static -static-libgcc -static-libstdc++" \
            -DCMAKE_SHARED_LINKER_FLAGS="-static -static-libgcc -static-libstdc++" \
            -DCMAKE_MODULE_LINKER_FLAGS="-static -static-libgcc -static-libstdc++"
          
      - name: Build
        if: steps.cache.outputs.cache-hit != 'true'
        working-directory: build
        run: |
          make -j${{ steps.cpu-cores.outputs.count }}
          
      - name: Install
        if: steps.cache.outputs.cache-hit != 'true'
        working-directory: build
        run: |
          make install
          
      - name: Archive
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          tar -cJvf build/${{ github.job }}.tar.xz -C ${{ env.PREFIX }} .
         
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ github.job }}
          path: build/${{ github.job }}.tar.xz
          retention-days: 3
          
  ffmpeg:
    name: "${{ github.job }}"
    runs-on: ubuntu-latest
    needs: [x264, x265, svtav1, opus]

    env:
      VERSION: ${{ github.event.inputs.ffmpeg-version }}
      PREFIX: ${{ github.event.inputs.prefix }}
      PKG_CONFIG_PATH: ${{ github.event.inputs.prefix }}/lib/pkgconfig
      CONFIGURE: >-
        --disable-debug
        --disable-doc
        --disable-ffplay
        --disable-ffprobe
        --prefix="${{ github.event.inputs.prefix }}"
        --pkg-config-flags="--static"
        --extra-libs="-lpthread -lm -lz"
        --extra-ldexeflags="-static"
        --enable-gpl
        --enable-version3
        --enable-nonfree
        --enable-static
        --disable-libxcb
        --enable-libopus
        --enable-libx264
        --enable-libsvtav1

    steps:
      - name: Get number of CPU cores
        uses: SimenB/github-actions-cpu-cores@v1
        id: cpu-cores
    
      - uses: actions/cache@v3
        id: cache
        with:
          path: |
            ${{ github.workspace }}/src
            ${{ github.workspace }}/build
            ${{ github.event.inputs.prefix }}
          key: ${{ github.job }}-${{ runner.os }}-${{ github.event.inputs.cache_id }}
       
      - name: Download x264
        if: steps.cache_sysroot.outputs.cache-hit != 'true'
        uses: actions/download-artifact@v3
        with:
          name: x264
          path: ${{ env.PREFIX }}
       
      - name: Download x265
        if: steps.cache_sysroot.outputs.cache-hit != 'true'
        uses: actions/download-artifact@v3
        with:
          name: x265
          path: ${{ env.PREFIX }}

      - name: Download svtav1
        if: steps.cache_sysroot.outputs.cache-hit != 'true'
        uses: actions/download-artifact@v3
        with:
          name: svtav1
          path: ${{ env.PREFIX }}

      - name: Download opus
        if: steps.cache_sysroot.outputs.cache-hit != 'true'
        uses: actions/download-artifact@v3
        with:
          name: opus
          path: ${{ env.PREFIX }}
      
      - name: Extract
        if: steps.cache_sysroot.outputs.cache-hit != 'true'
        working-directory: ${{ env.PREFIX }}
        run: |
          tar -xJf x264.tar.xz
          tar -xJf x265.tar.xz
          tar -xJf svtav1.tar.xz
          tar -xJf opus.tar.xz
          rm *.tar.xz
          
      - name: Install build dependency
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          sudo apt-get install -qq -y nasm yasm

      - name: Download sources
        run: |
          git clone -b ${{ env.VERSION }} --depth 1 https://git.ffmpeg.org/ffmpeg src
          mkdir build

      - name: Configure
        working-directory: build
        run: |
          export PATH="$PATH:${{ env.PREFIX }}/bin"
          ../src/configure ${{ env.CONFIGURE }}
          
      - name: Build
        if: steps.cache.outputs.cache-hit != 'true'
        working-directory: build
        run: |
          export PATH="$PATH:${{ env.PREFIX }}/bin"
          make -j${{ steps.cpu-cores.outputs.count }}
          
      - name: Install
        if: steps.cache.outputs.cache-hit != 'true'
        working-directory: build
        run: |
          make install
          
      - name: Archive
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          tar -cJvf build/${{ github.job }}.tar.xz -C ${{ env.PREFIX }} .
          
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ github.job }}
          path: build/${{ github.job }}.tar.xz
          retention-days: 3
