name: gcc toolchain

on:
  workflow_dispatch:
    inputs:
      arch:
        description: The architecture of platform
        required: true
        default: x86_64
      build:
        description: The build platform
        required: true
        default: x86_64-pc-linux-gnu
      target:
        description: The target platform
        required: true
        default: x86_64-unknown-linux-gnu
      kernel_url:
        description: The source tarball of linux kernel
        required: true
        default: "https://cdn.kernel.org/pub/linux/kernel/v5.x/linux-5.17.2.tar.xz"
      binutils_version:
        description: The version of binutils
        required: true
        default: "2.38"
      gcc_version:
        description: The version of gcc
        required: true
        default: "11.2.0"
      glibc_version:
        description: The version of glibc
        required: true
        default: "2.35"
      sysroot:
        description: The root for gcc toolchain
        required: true
        default: /opt/gcc
      cache_id:
        description: The build id for caches
        required: true
        default: "1"

jobs:
  binutils:
    name: "${{ github.job }}"
    runs-on: ubuntu-latest
    continue-on-error: true

    env:
      ARCH: ${{ github.event.inputs.arch }}
      TARGET: ${{ github.event.inputs.target }}
      SYSROOT: ${{ github.event.inputs.sysroot }}
      VERSION: ${{ github.event.inputs.binutils_version }}
      CONFIGURE: >-
        --prefix=${{ github.event.inputs.sysroot }}/tools
        --with-sysroot=${{ github.event.inputs.sysroot }}
        --build=${{ github.event.inputs.build }}
        --host=${{ github.event.inputs.build }}
        --target=${{ github.event.inputs.target }}
        --disable-nls
        --disable-multilib
        --disable-werror

    steps:
      - name: Get number of CPU cores
        uses: SimenB/github-actions-cpu-cores@v1
        id: cpu-cores

      - uses: actions/cache@v3
        id: cache
        with:
          path: |
            ${{ github.workspace }}/src
            ${{ github.workspace }}/build
          key: ${{ github.job }}-${{ runner.os }}-${{ github.event.inputs.cache_id }}
        
      - name: Download sources
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          curl -sSL https://ftp.gnu.org/gnu/binutils/binutils-${{ env.VERSION }}.tar.xz -o binutils.tar.xz
          tar -xJf binutils.tar.xz
          rm binutils.tar.xz
          mv binutils* src
          mkdir build

      - name: Configure
        if: steps.cache.outputs.cache-hit != 'true'
        working-directory: build
        run: |
          ../src/configure ${{ env.CONFIGURE }}

      - name: Build
        if: steps.cache.outputs.cache-hit != 'true'
        working-directory: build
        run: |
          make -j${{ steps.cpu-cores.outputs.count }}
      
      - name: Install
        working-directory: build
        run: |
          make install
      
      - name: Archive
        working-directory: /opt
        run: |
          tar -cJvf /tmp/${{ github.job }}.tar.xz -C ${{ env.SYSROOT }} .
         
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ github.job }}
          path: /tmp/${{ github.job }}.tar.xz
          retention-days: 3

  kernel_headers:
    name: "${{ github.job }}"
    runs-on: ubuntu-latest
    continue-on-error: true

    env:
      ARCH: ${{ github.event.inputs.arch }}
      TARGET: ${{ github.event.inputs.target }}
      SYSROOT: ${{ github.event.inputs.sysroot }}
      VERSION: ${{ github.event.inputs.kernel_url }}

    steps:
      - name: Get number of CPU cores
        uses: SimenB/github-actions-cpu-cores@v1
        id: cpu-cores

      - uses: actions/cache@v3
        id: cache
        with:
          path: |
            ${{ github.workspace }}/src
            ${{ github.workspace }}/build
          key: ${{ github.job }}-${{ runner.os }}-${{ github.event.inputs.cache_id }}
        
      - name: Download sources
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          curl -sSL ${{ env.VERSION }} -o kernel.tar.xz
          tar -xJf kernel.tar.xz
          rm kernel.tar.xz
          mv linux* src
          
      - name: Install
        working-directory: src
        run: |
          make ARCH=${{ env.ARCH }} INSTALL_HDR_PATH=${{ env.SYSROOT }}/usr headers_install
      
      - name: Archive
        working-directory: /opt
        run: |
          tar -cJvf /tmp/${{ github.job }}.tar.xz -C ${{ env.SYSROOT }} .
         
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ github.job }}
          path: /tmp/${{ github.job }}.tar.xz
          retention-days: 3
          
  gcc_glibc:
    name: "${{ github.job }}"
    runs-on: ubuntu-latest
    needs: [binutils, kernel_headers]
    continue-on-error: true

    env:
      ARCH: ${{ github.event.inputs.arch }}
      TARGET: ${{ github.event.inputs.target }}
      SYSROOT: ${{ github.event.inputs.sysroot }}
      GCC_CONFIGURE: >-
        --prefix=${{ github.event.inputs.sysroot }}/tools
        --build=${{ github.event.inputs.build }}
        --host=${{ github.event.inputs.build }}
        --target=${{ github.event.inputs.target }}
        --with-sysroot=${{ github.event.inputs.sysroot }}
        --with-glibc-version=${{ github.event.inputs.glibc_version }}
        --with-newlib
        --without-headers
        --enable-initfini-array
        --disable-nls
        --disable-werror
        --disable-multilib
        --disable-decimal-float
        --disable-threads
        --disable-libatomic
        --disable-libgomp
        --disable-libquadmath
        --disable-libssp
        --disable-libvtv
        --disable-libstdcxx
        --enable-languages=c,c++
      GLIBC_CONFIGURE: >-
        --prefix=/usr
        --build=${{ github.event.inputs.build }}
        --host=${{ github.event.inputs.target }}
        --target=${{ github.event.inputs.target }}
        --with-headers=${{ github.event.inputs.sysroot }}/usr/include
        --disable-multilib
        --without-selinux
        --enable-kernel=3.2

    steps:
      - name: Get number of CPU cores
        uses: SimenB/github-actions-cpu-cores@v1
        id: cpu-cores

      - uses: actions/cache@v3
        id: cache_sysroot
        with:
          path: ${{ github.event.inputs.sysroot }}
          key: ${{ github.job }}-${{ runner.os }}-${{ github.event.inputs.cache_id }}
      
      - name: Download binutils
        if: steps.cache_sysroot.outputs.cache-hit != 'true'
        uses: actions/download-artifact@v3
        with:
          name: binutils
          path: ${{ env.SYSROOT }}

      - name: Download kernel_headers
        if: steps.cache_sysroot.outputs.cache-hit != 'true'
        uses: actions/download-artifact@v3
        with:
          name: kernel_headers
          path: ${{ env.SYSROOT }}
      
      - name: Extract
        if: steps.cache_sysroot.outputs.cache-hit != 'true'
        working-directory: ${{ env.SYSROOT }}
        run: |
          tar -xJf binutils.tar.xz
          tar -xJf kernel_headers.tar.xz
          rm *.tar.xz

      - uses: actions/cache@v3
        id: cache
        with:
          path: |
            ${{ github.workspace }}/gcc
            ${{ github.workspace }}/build-gcc
            ${{ github.workspace }}/glibc
            ${{ github.workspace }}/build-glibc
          key: ${{ github.job }}-${{ runner.os }}-${{ github.event.inputs.cache_id }}
        
      - name: Download gcc sources
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          curl -sSL https://ftp.gnu.org/gnu/gcc/gcc-${{ github.event.inputs.gcc_version }}/gcc-${{ github.event.inputs.gcc_version }}.tar.xz -o gcc.tar.xz
          tar -xJf gcc.tar.xz
          rm gcc.tar.xz
          mv gcc* gcc
          pushd gcc
          contrib/download_prerequisites
          popd
          mkdir build-gcc

      - name: Download glibc sources
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          curl -sSL https://ftp.gnu.org/gnu/glibc/glibc-${{ github.event.inputs.glibc_version }}.tar.xz -o glibc.tar.xz
          tar -xJf glibc.tar.xz
          rm glibc.tar.xz
          mv glibc* glibc
          mkdir build-glibc

      - name: Update enviornment variables
        run: |
          echo "${{ env.SYSROOT }}/tools/bin" >> $GITHUB_PATH

      - name: Configure gcc
        if: steps.cache.outputs.cache-hit != 'true'
        working-directory: build-gcc
        run: |
          ../gcc/configure ${{ env.GCC_CONFIGURE }}

      - name: Configure glibc
        if: steps.cache.outputs.cache-hit != 'true'
        working-directory: build-glibc
        run: |
          ../glibc/configure ${{ env.GLIBC_CONFIGURE }}

      - name: Build baremetal gcc
        working-directory: build-gcc
        run: |
          make -j${{ steps.cpu-cores.outputs.count }} all-gcc
      
      - name: Install baremetal gcc
        working-directory: build-gcc
        run: |
          make install-gcc

      - name: Install glibc runtimes
        working-directory: build-glibc
        run: |
          make install-bootstrap-headers=yes DESTDIR=${{ env.SYSROOT }} install-headers
          make -j${{ steps.cpu-cores.outputs.count }} csu/subdir_lib
          mkdir -p ${{ env.SYSROOT }}/lib
          install csu/crt1.o csu/crti.o csu/crtn.o ${{ env.SYSROOT }}/lib
          ${{ github.event.inputs.target }}-gcc -nostdlib -nostartfiles -shared -x c /dev/null -o ${{ env.SYSROOT }}/lib/libc.so
          touch ${{ env.SYSROOT }}/usr/include/gnu/stubs.h
          
      - name: Build libgcc
        working-directory: build-gcc
        run: |
          make -j${{ steps.cpu-cores.outputs.count }} all-target-libgcc
      
      - name: Install libgcc
        working-directory: build-gcc
        run: |
          make install-target-libgcc

      - name: Build glibc
        working-directory: build-glibc
        run: |
          make -j${{ steps.cpu-cores.outputs.count }}

      - name: Install glibc
        working-directory: build-glibc
        run: |
          make DESTDIR=${{ env.SYSROOT }} install

      - name: Build gcc
        working-directory: build
        run: |
          make -j${{ steps.cpu-cores.outputs.count }}
      
      - name: Install gcc
        working-directory: build
        run: |
          make
      
      - name: Archive
        working-directory: /opt
        run: |
          tar -cJvf /tmp/${{ github.job }}.tar.xz -C ${{ env.SYSROOT }} .
         
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ github.job }}
          path: /tmp/${{ github.job }}.tar.xz
          retention-days: 3
          
  