name: gcc

on:
  workflow_dispatch:
    inputs:
      version:
        description: The version of gcc
        required: true
        default: "11.2.0"
      dist:
        description: The path to install
        required: true
        default: gcc-11

jobs:
  gcc:
    strategy:
      matrix:
        include:
          - name: linux_amd64
            os: ubuntu-latest

    name: "${{ github.job }} ${{ matrix.name }}"
    runs-on: ${{ matrix.os }}
    continue-on-error: true

    env:
      VERSION: ${{ github.event.inputs.version }}
      SRC: ${{ github.workspace }}/src
      BUILD: ${{ github.workspace }}/build
      DIST: ${{ github.event.inputs.dist }}
      CONFIGURE: >-
        --prefix=/opt/${{ github.event.inputs.dist }}
        --enable-bootstrap
        --enable-languages=c,c++
        --enable-threads=posix
        --enable-checking=release
        --disable-multilib
        --with-system-zlib
      EXTRA_CONFIGURE: ${{ matrix.EXTRA_CONFIGURE }}

    steps:
      - name: Get number of CPU cores
        uses: SimenB/github-actions-cpu-cores@v1
        id: cpu-cores
        
      - uses: actions/checkout@v3
        with:
          repository: gcc-mirror/gcc
          ref: releases/gcc-${{ env.VERSION }}
          path: ${{ env.SRC }}
          
      - name: Create build directory
        run: |
          mkdir ${{ env.BUILD }}
          
      - name: Download dependencies
        working-directory: ${{ env.SRC }}
        run: |
          ./contrib/download_prerequisites

      - name: Configure
        working-directory: ${{ env.BUILD }}
        run: |
          ${{ env.SRC }}/configure ${{ env.CONFIGURE }}

      - name: Build
        working-directory: ${{ env.BUILD }}
        run: |
          make -j ${{ steps.cpu-cores.outputs.count }}
      
      - name: Install
        working-directory: ${{ env.BUILD }}
        run: |
          make install
      
      - name: Archive
        working-directory: /opt
        run: |
          tar -cJvf /tmp/archive.tar.xz ${{ env.DIST }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ github.job }}-${{ env.VERSION }}-${{ matrix.name }}
          path: /tmp/archive.tar.xz
