name: GCC

on:
  workflow_dispatch:
    inputs:
      version:
        description: The version of GCC
        required: true
        default: releases/gcc-11.2.0
      install_path:
        description: The version of GCC
        required: true
        default: /opt/gcc-11

jobs:
  gcc:
    strategy:
      matrix:
        include:
          - name: linux_amd64
            os: ubuntu-latest

    name: "GCC ${{ matrix.name }}"
    runs-on: ${{ matrix.os }}
    continue-on-error: true

    env:
      VERSION: ${{ github.event.inputs.version }}
      SRC: ${{ github.workspace }}/gcc
      BUILD: ${{ github.workspace }}/build
      CONFIGURE: >-
        --prefix=${{ github.event.inputs.install_path }}
        --enable-languages=c,c++
        --enable-threads=posix
        --enable-checking=release
        --disable-multilib
        --with-system-zlib
      EXTRA_CONFIGURE: ${{ matrix.EXTRA_CONFIGURE }}

    steps:
      - uses: actions/checkout@v2
        with:
          repository: gcc-mirror/gcc
          ref: ${{ env.VERSION }}
          path: ${{ env.SRC }}
          
      - name: Create build directory
        run: |
          mkdir ${{ env.BUILD }}
          
      - name: Download dependencies
        working-directory: ${{ env.SRC }}
        run: |
          ./contrib/download_prerequisites

      - name: Configure
        working-directory: ${{ env.BUILD }}
        run: |
          ${{ env.SRC }}/configure ${{ env.CONFIGURE }}

      - name: Build
        working-directory: ${{ env.BUILD }}
        run: |
          make -j 16
      
      - name: Install
        working-directory: ${{ env.BUILD }}
        run: |
          make install

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: ${{ github.job }}-${{ env.VERSION }}-${{ matrix.name }}
          path: ${{ github.event.inputs.version }}
