name: glibc

on:
  workflow_dispatch:
    inputs:
      version:
        description: The version of glibc
        required: true
        default: "2.35"
      kernel:
        description: The source tarball of linux kernel
        required: true
        default: "https://cdn.kernel.org/pub/linux/kernel/v5.x/linux-5.17.2.tar.xz"

jobs:
  gcc:
    strategy:
      matrix:
        include:
          - name: linux_amd64
            os: ubuntu-latest

    name: "glibc ${{ matrix.name }}"
    runs-on: ${{ matrix.os }}
    continue-on-error: true

    env:
      VERSION: ${{ github.event.inputs.version }}
      SRC: ${{ github.workspace }}/src
      BUILD: ${{ github.workspace }}/build
      CONFIGURE: >-
        --prefix=/usr
        --enable-kernel=4.15
        --with-headers=/opt/kernel/usr
        libc_cv_slibdir=/opt/glibc/usr/lib
      EXTRA_CONFIGURE: ${{ matrix.EXTRA_CONFIGURE }}

    steps:
      - name: Download kernel sources
        run: |
          curl -sSL ${{ env.kernel }} -o kernel.tar.xz
          tar -xJf kernel.tar.xz
          ls
          cd kernel*
          make headers
          find usr/include -name '.*' -delete
          rm usr/include/Makefile
          cp -rv usr/include /opt/kernel/usr
          ls /opt/kernel/usr
    
      - name: Download sources
        run: |
          curl -sSL https://ftp.gnu.org/gnu/glibc/glibc-${{ env.VERSION }}.tar.xz -o glibc.tar.xz
          tar -xJf glibc.tar.xz
          mv glibc-${{ env.VERSION }} ${{ env.SRC }}
          ls
          
      - name: Create build directory
        run: |
          mkdir -p ${{ env.BUILD }}
          mkdir -p /opt/glib/usr

      - name: Configure
        working-directory: ${{ env.BUILD }}
        run: |
          ${{ env.SRC }}/configure ${{ env.CONFIGURE }}

      - name: Build
        working-directory: ${{ env.BUILD }}
        run: |
          make -j 16
      
      - name: Install
        working-directory: ${{ env.BUILD }}
        run: |
          make DESTDIR=/opt/glibc install
      
      - name: Archive
        working-directory: /opt
        run: |
          tar -cJvf archive.tar.xz /opt/glibc
         
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: ${{ github.job }}-${{ env.VERSION }}-${{ matrix.name }}
          path: /opt/archive.tar.xz
